# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set arguments for POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

# Set the environment variables for the PostgreSQL database
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

# Copy the SQL scripts to the container
COPY ./db/init.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432