# Use the official Python base image
FROM python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .
COPY .../kea.whl .
COPY /app/ .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Specify the command to run when the container starts
CMD [ "python", "app.py" ]